---
# file: ansible-role-common/tasks/add-ssh-key-auth-file.yaml
- name: Add ssh key to authorized_keys file
  authorized_key:
    user: "{{ ansible_new_user }}"
    state: present
    key: "{{ lookup('file', '{{ ansible_pub_key }}') }}"
    comment: "{{ lookup('file','/etc/hostname') }}"
