---
# file: ansible-role-common/tasks/main.yaml
- include: create-group.yaml
  become: true

- include: create-new-ansible-user.yaml
  become: true

- include: add-ssh-key-auth-file.yaml
  become: true
  tags:
    - push_ssh_key

- include: push-sshd_config.yaml
  tags:
    - push_sshd_config

- include: set-hostname.yaml
  tags:
    - set_hostname

- name: Reboot the server
  reboot:
  become: true
  when: set_hostname is changed
