---
# file: ansible-role-common/tasks/push-sshd_config.yaml

- name: Find Connected Client IP 
  become: false
  debug:
    msg: "{{ ansible_env.SSH_CLIENT.split(' ') | first }}"
  register: local_ip_addr


- name: Push sshd_config
  become: true
  template:
    src="sshd_config.j2" dest="/etc/ssh/sshd_config.new" backup=yes
